// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScmUIClient is the client API for ScmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScmUIClient interface {
	// ListContractSpecs returns a list of Contract(s) that can be started through the UI.
	ListContractSpecs(ctx context.Context, in *ListContractSpecsRequest, opts ...grpc.CallOption) (ScmUI_ListContractSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type scmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewScmUIClient(cc grpc.ClientConnInterface) ScmUIClient {
	return &scmUIClient{cc}
}

func (c *scmUIClient) ListContractSpecs(ctx context.Context, in *ListContractSpecsRequest, opts ...grpc.CallOption) (ScmUI_ListContractSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ScmUI_ServiceDesc.Streams[0], "/v1.ScmUI/ListContractSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &scmUIListContractSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ScmUI_ListContractSpecsClient interface {
	Recv() (*ListContractSpecsResponse, error)
	grpc.ClientStream
}

type scmUIListContractSpecsClient struct {
	grpc.ClientStream
}

func (x *scmUIListContractSpecsClient) Recv() (*ListContractSpecsResponse, error) {
	m := new(ListContractSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *scmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ScmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScmUIServer is the server API for ScmUI service.
// All implementations must embed UnimplementedScmUIServer
// for forward compatibility
type ScmUIServer interface {
	// ListContractSpecs returns a list of Contract(s) that can be started through the UI.
	ListContractSpecs(*ListContractSpecsRequest, ScmUI_ListContractSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedScmUIServer()
}

// UnimplementedScmUIServer must be embedded to have forward compatible implementations.
type UnimplementedScmUIServer struct {
}

func (UnimplementedScmUIServer) ListContractSpecs(*ListContractSpecsRequest, ScmUI_ListContractSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListContractSpecs not implemented")
}
func (UnimplementedScmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedScmUIServer) mustEmbedUnimplementedScmUIServer() {}

// UnsafeScmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScmUIServer will
// result in compilation errors.
type UnsafeScmUIServer interface {
	mustEmbedUnimplementedScmUIServer()
}

func RegisterScmUIServer(s grpc.ServiceRegistrar, srv ScmUIServer) {
	s.RegisterService(&ScmUI_ServiceDesc, srv)
}

func _ScmUI_ListContractSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListContractSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScmUIServer).ListContractSpecs(m, &scmUIListContractSpecsServer{stream})
}

type ScmUI_ListContractSpecsServer interface {
	Send(*ListContractSpecsResponse) error
	grpc.ServerStream
}

type scmUIListContractSpecsServer struct {
	grpc.ServerStream
}

func (x *scmUIListContractSpecsServer) Send(m *ListContractSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ScmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ScmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScmUI_ServiceDesc is the grpc.ServiceDesc for ScmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ScmUI",
	HandlerType: (*ScmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ScmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListContractSpecs",
			Handler:       _ScmUI_ListContractSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "scm-ui.proto",
}
